### ISSUE TITLE
java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/base/Predicate

### ISSUE THREAD

**Issue by thomaspreis** [kumuluz/kumuluzee-samples#15]
Hello guys,

I'm creating a Rest Service using Kumuluzee, the service itself it runs fine. Then I included the swagger using the sample project [kumuluzee-swagger](https://github.com/kumuluz/kumuluzee-samples/tree/master/kumuluzee-swagger) as a basis. 
When I startup the application I get this error:

`java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/base/Predicate
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:419)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:386)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.kumuluz.ee.jetty.JettyServletServer.startServer(JettyServletServer.java:81)
        at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:368)
        at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:73)
        at com.kumuluz.ee.EeApplication.main(EeApplication.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.kumuluz.ee.loader.EeClassLoader.invokeMain(EeClassLoader.java:434)
        at com.kumuluz.ee.loader.EeBootLoader.launch(EeBootLoader.java:54)
        at com.kumuluz.ee.loader.EeBootLoader.main(EeBootLoader.java:41)
Caused by: java.lang.ClassNotFoundException: Failure to load: jersey.repackaged.com.google.common.base.Predicate
        at com.kumuluz.ee.loader.EeClassLoader.loadClass(EeClassLoader.java:488)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 30 more`

The class jersey.repackaged.com.google.common.base.Predicate is not present in the workspace, but the original one it is com.google.common.base.Predicate. Is there any configuration missing?

**Comment by thomaspreis** [comment]
The dependency was missing:

`		<dependency>
			<groupId>com.kumuluz.ee</groupId>
			<artifactId>kumuluzee-jax-rs-jersey</artifactId>
		</dependency>`

After added it, the error stopped. However there is a warning when the application is started:

`2018-10-12 10:54:56,244 INFO  Found extension implemented by Swagger {}  
2018-10-12 10:54:56,244 INFO  Initializing Swagger extension. {}  
2018-10-12 10:54:56,383 WARN  Multiple JAX-RS applications not supported. Swagger definitions will not be served. {}  
2018-10-12 10:54:56,383 INFO  Found extension implemented by Swagger-UI {}  `

**Comment by thomaspreis** [comment]
After removing the dependency:

> 			<groupId>com.kumuluz.ee.rest</groupId>
			<artifactId>kumuluzee-rest-core</artifactId>

It worked fine, I will close the issue.
